#!/usr/bin/env node
// @ts-check
import { text } from "node:stream/consumers";

/**
 * @type {{
 *  id: number, name: string, size: number, iconURL: string, developer: string,
 *  categories: string[]
 * }[]}
 */
const apps = JSON.parse(await text(process.stdin));

apps.sort((b, a) => a.size - b.size);

let total = 0;
let count = 0;

for (const app of apps) {
  if (app.categories.includes("Games")) continue;
  total += app.size;
  ++count;
}

const avgSize = total / count;

const categories = Array.from(
  apps.reduce(
    (s, a) => (s.add(a.categories[0]), s),
    /** @type {Set<string>} */ (new Set())
  )
);

categories.sort();

const developers = Array.from(
  apps.reduce(
    (s, a) => (s.add(a.developer), s),
    /** @type {Set<string>} */ (new Set())
  )
);

developers.sort();

const stores = ["ae", "br", "de", "fr", "gb", "jp", "us"];

/**
 *
 * @param s {string}
 */
function slugify(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s-]+/g, "")
    .replace(/[\s-]+/g, "-");
}

/**
 *
 * @param s {string}
 */
function escapeHTML(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 *
 * @param bytes {number}
 */
function formatSize(bytes) {
  if (bytes >= 1000 ** 3) return `${(bytes / 1000 ** 3).toFixed(2)} GB`;
  if (bytes >= 1000 ** 2) return `${(bytes / 1000 ** 2).toFixed(2)} MB`;
  if (bytes >= 1000 ** 1) return `${(bytes / 1000 ** 1).toFixed(2)} KB`;
  return `${bytes} B`;
}

const indent = (/** @type {number} */ n) => "\n" + "  ".repeat(n);

process.stdout.write(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="color-scheme" content="light dark">
    <meta name="viewport" content="initial-scale=1">
    <title>App Bloat Leaderboard</title>
    <style>
      body {
        font-family: sans-serif;
      }
      header {
        text-align: center;
      }
      .apps {
        max-width: 50rem;
        margin: 0 auto;
        padding-left: 4rem;
      }
      .app {
        font-size: 1.5rem;
        margin: 0.5rem 0;
        display: none;
      }
      .app .icon {
        vertical-align: middle;
        border-radius: 0.5rem;
      }
      .app .size {
        color: gray;
      }
      header:has(option[value=""]:checked) ~ .apps .app:not([data-categories~=games]),
      header:has(option[value=all]:checked) ~ .apps .app[data-categories],
      ${categories
        .map(
          (g) =>
            `header:has(option[value=${slugify(
              g
            )}]:checked) ~ .apps .app[data-categories~=${slugify(g)}]`
        )
        .join("," + indent(3))} {
        display: list-item;
      }
    </style>
  </head>
  <body>
    <header>
      <h1>App Bloat Leaderboard</h1>
      <form>Top
        <select name="category">
          <option value>Free</option>
          <option value="all">Free & Games</option>
          ${categories
            .map(
              (g) => `<option value="${slugify(g)}">${escapeHTML(g)}</option>`
            )
            .join(indent(5))}
        </select>
        apps in the
        <select id="store">
          ${stores
            .map((s) => `<option value="${s}">${s.toUpperCase()}</option>`)
            .join(indent(5))}
        </select>
        App Store, ordered by size
        <p>
          <datalist id="developers">
            ${developers
              .map((d) => `<option value="${escapeHTML(d)}"></option>`)
              .join(indent(6))}
          </datalist>
          <input type="text" name="developer" list="developers"
            placeholder="Developer">
        </p>
        <label>Average size: <output>${formatSize(avgSize)}</output></label>
      </form>
    </header>
    <script>
      ${formatSize.toString()}

      function calculateAvgSize() {
        let total = 0;
        let len = 0;
        for (const appEl of document.querySelectorAll('.app')) {
          if (
            (developerInput.value &&
              appEl.dataset.developer != developerInput.value) ||
            (categoryInput.value != 'all' &&
              (categoryInput.value ?
                !appEl.dataset.categories.split(' ').includes(categoryInput.value) :
                appEl.dataset.categories.split(' ').includes('games')))
          )
            continue;
          total += Number(appEl.dataset.size);
          ++len;
        }
        document.querySelector('output').textContent = formatSize(total / len);
      }

      const params = new URLSearchParams(location.search);

      const category = params.get('category');
      const categoryInput = document.querySelector('[name=category]');
      if (category) categoryInput.value = category;
      categoryInput.onchange = () => {
        calculateAvgSize();
        const url = new URL(location.href);
        if (categoryInput.value)
          url.searchParams.set('category', categoryInput.value);
        else url.searchParams.delete('category');
        history.pushState(
          { ...history.state, category: categoryInput.value }, '',
          url.toString()
        );
      };

      const storeInput = document.querySelector('#store');
      const store = location.pathname.split('/').pop().replace(/\\.html$/, '');
      storeInput.onchange = () => {
        form.action = storeInput.value;
        form.submit();
      };
      storeInput.value =
        Array.from(storeInput.options).find(o => o.value == store)?.value ??
        'us';

      const developer = params.get('developer');
      const developerInput = document.querySelector('[name=developer]');
      function filterDevelopers() {
        for (const appEl of document.querySelectorAll('.app')) {
          appEl.style.display =
            !developerInput.value ||
            appEl.dataset.developer == developerInput.value
            ? '' : 'none';
        }
      }
      developerInput.onchange = () => {
        filterDevelopers();
        calculateAvgSize();
        const url = new URL(location.href);
        if (developerInput.value)
          url.searchParams.set('developer', developerInput.value);
        else url.searchParams.delete('developer');
        history.pushState(
          { ...history.state, developer: developerInput.value }, '',
          url.toString()
        );
      }
      if (developer) developerInput.value = developer;

      const form = document.querySelector('form');
      form.onformdata = ({ formData }) => {
        if (!formData.get('category')) formData.delete('category');
        if (!formData.get('developer')) formData.delete('developer');
      };

      window.onpopstate = (event) => {
        categoryInput.value = event.state?.category ?? '';
        developerInput.value = event.state?.developer ?? '';
        filterDevelopers();
        calculateAvgSize();
      };
    </script>
    <ol class="apps">
      ${apps
        .map(
          (app) =>
            `<li class="app" data-size="${
              app.size
            }" data-developer="${escapeHTML(
              app.developer
            )}" data-categories="${app.categories
              .map(slugify)
              .join(" ")}"><img class="icon" alt="App icon for ${escapeHTML(
              app.name
            )}" src="${app.iconURL}" height="48"> <bdi>${escapeHTML(
              app.name
            )}</bdi> <small class="size">${formatSize(app.size)}</small></li>`
        )
        .join(indent(3))}
    </ol>
    <script>filterDevelopers(); calculateAvgSize();</script>
  </body>
</html>
`);
