#!/bin/sh

set -euo pipefail

store=${1-us}

{ for chartId in 36 $(seq 6000 6027); do
	case $chartId in
	6019) continue ;;
	6022) continue ;;
	6025) continue
	esac
	./get-top-apps "$store" "$chartId" 100 |
	jq -c --unbuffered ".[] + {\"chartId\":\"$chartId\"}" &
done; for j in $(jobs -p); do wait $j; done; } |
jq -s '
	group_by(.id) |
	map((.[0] | del(.chartId)) + { chartIds: map(.chartId) | sort })
'
