#!/usr/bin/env node
// @ts-check
async function getTopApps(store = "us", genre = "36", limit = 100) {
  let res = await fetch(
    `https://itunes.apple.com/${store}/rss/topfreeapplications/genre=${genre}/limit=${limit}/json`
  );
  if (!res.ok) throw new Error("Failed to get top apps");

  /** @type {{ feed: { entry: { id: { attributes: { 'im:id': string }}}[] }}} */
  const {
    feed: { entry: apps },
  } = await res.json();

  if (!apps) return [];

  const appIds = apps.map((app) => app.id.attributes["im:id"]);

  res = await fetch(`https://itunes.apple.com/lookup?id=${appIds.join(",")}`);
  if (!res.ok) throw new Error("Failed to get apps");

  /**
   * @type {{
   *  results: {
   *    trackId: number,
   *    trackName: string,
   *    artistName: string,
   *    fileSizeBytes: string,
   *    artworkUrl100: string,
   *    genres: string[]
   *  }[]
   * }}
   */
  const { results } = await res.json();

  return results.map(
    ({
      trackId: id,
      trackName: name,
      artistName: developer,
      fileSizeBytes: size,
      artworkUrl100: iconURL,
      genres: categories,
    }) => ({
      id,
      name,
      developer,
      iconURL,
      size: Number(size),
      categories,
    })
  );
}

process.stdout.write(
  // @ts-expect-error await is allowed here
  JSON.stringify(await getTopApps(process.argv[2], process.argv[3]), null, 2)
);
